# Generated by Django 2.2.10 on 2021-03-22 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.CheckList')),
            ],
        ),
        migrations.AlterField(
            model_name='subsection',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Section'),
        ),
    ]
