# Generated by Django 2.2.10 on 2021-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20210322_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn_text',
            field=models.TextField(max_length=2000),
        ),
    ]
