# Generated by Django 2.2.10 on 2021-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.IntegerField()),
                ('tenant', models.CharField(max_length=100)),
                ('auditor', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
