# Generated by Django 2.2.10 on 2021-03-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audits',
            table='audits',
        ),
    ]
