# Generated by Django 2.2.10 on 2021-03-23 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(max_length=500)),
                ('section', models.CharField(max_length=500)),
                ('subsection', models.CharField(max_length=500)),
                ('question', models.CharField(max_length=1000)),
                ('question_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('tenant_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='audit.TenantLocation')),
            ],
        ),
    ]
