# Generated by Django 2.2.10 on 2021-03-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantlocation',
            name='intitution',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
