# Generated by Django 2.2.10 on 2021-03-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_tenantlocation_intitution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantlocation',
            old_name='intitution',
            new_name='institution',
        ),
    ]
