# Generated by Django 2.2.10 on 2021-03-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20210323_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='comment',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
