# Generated by Django 2.2.10 on 2021-03-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_checklistinstance_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
