# Generated by Django 2.2.10 on 2021-03-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20210324_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='tenant_location',
            field=models.CharField(max_length=50),
        ),
    ]
