# Generated by Django 2.2.10 on 2021-03-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20210324_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=500)),
                ('business_name', models.CharField(max_length=500)),
                ('lease_end_date', models.DateField(blank=True)),
                ('UEN', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='TenantLocation',
        ),
    ]
