# Generated by Django 2.2.10 on 2021-04-05 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_delete_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='auditor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 7, 31, 30, 629040, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
