# Generated by Django 2.2.10 on 2021-04-08 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_auto_20210406_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 8)),
        ),
    ]
