# Generated by Django 2.2.10 on 2021-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_auto_20210409_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_location', models.CharField(max_length=50)),
                ('tenant', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('checklist_id', models.IntegerField()),
            ],
        ),
    ]
