# Generated by Django 2.2.10 on 2021-04-09 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_scoretable'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretable',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 9)),
            preserve_default=False,
        ),
    ]
