# Generated by Django 2.2.10 on 2021-04-09 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_scoretable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretable',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 9)),
        ),
    ]
