# Generated by Django 2.2.10 on 2021-04-16 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_auto_20210409_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 16)),
        ),
        migrations.AlterField(
            model_name='scoretable',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 16)),
        ),
    ]
