# Generated by Django 2.2.10 on 2021-04-19 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_auto_20210416_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretable',
            name='checklist_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistinstance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
        ),
        migrations.AlterField(
            model_name='scoretable',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
        ),
    ]
