# Generated by Django 2.2.10 on 2021-04-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0021_auto_20210419_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretable',
            name='non_compliance',
            field=models.BooleanField(default=False),
        ),
    ]
