# Generated by Django 2.2.10 on 2021-04-18 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0021_auto_20210416_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 18)),
        ),
        migrations.AlterField(
            model_name='scoretable',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 18)),
        ),
    ]
