# Generated by Django 2.2.10 on 2021-04-18 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0022_auto_20210418_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
        ),
        migrations.AlterField(
            model_name='scoretable',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
        ),
    ]
