# Generated by Django 2.2.10 on 2021-04-20 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_auto_20210420_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectificationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date(2021, 4, 20))),
                ('original_date', models.DateField()),
                ('comment', models.CharField(max_length=1000)),
                ('tenant', models.CharField(max_length=50)),
                ('update', models.CharField(max_length=1000)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('row_id', models.IntegerField()),
                ('checklist_type', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
