# Generated by Django 2.2.10 on 2021-04-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0024_rectificationtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rectificationtable',
            old_name='original_date',
            new_name='date_due',
        ),
    ]
