# Generated by Django 2.2.10 on 2021-04-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0025_auto_20210420_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
