# Generated by Django 2.2.10 on 2021-04-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0026_checklistinstance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistinstance',
            old_name='status',
            new_name='appeal_status',
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='rect_status',
            field=models.IntegerField(null=True),
        ),
    ]
