# Generated by Django 2.2.10 on 2021-04-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0028_auto_20210421_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 22)),
        ),
        migrations.AlterField(
            model_name='rectificationtable',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 22)),
        ),
        migrations.AlterField(
            model_name='scoretable',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 22)),
        ),
    ]
