# Generated by Django 2.2.10 on 2021-04-19 13:51

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_appealalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealalert',
            name='comment',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appealalert',
            name='original_date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appealalert',
            name='row_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appealalert',
            name='tenant',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
