# Generated by Django 2.2.10 on 2021-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210419_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealalert',
            name='checklist_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
