# Generated by Django 2.2.10 on 2021-04-19 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_appealalert_checklist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealalert',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 20)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 20)),
        ),
    ]
