# Generated by Django 2.2.10 on 2021-04-20 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20210420_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectificationAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date(2021, 4, 20))),
                ('row_id', models.IntegerField()),
            ],
        ),
    ]
