# Generated by Django 2.2.10 on 2021-04-21 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_rectificationalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealalert',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 21)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 21)),
        ),
        migrations.AlterField(
            model_name='rectificationalert',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 21)),
        ),
    ]
