# Generated by Django 2.2.10 on 2021-04-22 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20210421_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appealalert',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 22)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 22)),
        ),
        migrations.AlterField(
            model_name='rectificationalert',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 22)),
        ),
    ]
