# Generated by Django 2.2.10 on 2021-04-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20210422_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tenant',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
